version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true


  database-up:
    cmds:
      - docker compose -f ./docker/database/database.yml up -d

  database-down:
    cmds:
      - docker compose -f ./docker/database/database.yml down -v

  migrate-up :
    cmds:
      -  migrate -path docker/database/migration/dev -database "postgresql://user:password@university.grade.database.fr:5432/grade_dev?sslmode=disable" -verbose up
      -  migrate -path docker/database/migration/test -database "postgresql://user:password@university.grade.database.fr:5432/grade_test?sslmode=disable" -verbose up

  migrate-down :
    cmds:
      -  migrate -path docker/database/migration/dev -database "postgresql://user:password@university.grade.database.fr:5432/grade_dev?sslmode=disable" -verbose down
      -  migrate -path docker/database/migration/test -database "postgresql://user:password@university.grade.database.fr:5432/grade_test?sslmode=disable" -verbose down

  createdbs:
    cmds:
      - docker exec -it grade_database createdb --username=user --owner=user grade_dev
      - docker exec -it grade_database createdb --username=user --owner=user grade_test

  dropdbs:
    cmds:
      - docker exec -it grade_database drop grade_dev
      - docker exec -it grade_database drop grade_test

  sqlc:
    cmds:
      - sqlc generate

  test:
    cmds:
      - go test -v -cover ./...