// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package grade_database

import (
	"database/sql"
)

type Course struct {
	ID         int32
	CourseName string
	UniteID    sql.NullInt32
}

type CourseAverage struct {
	ID         int32
	CourseName string
	Average    int32
}

type Grade struct {
	ID          int32
	GradeNumber int32
	CourseName  string
	StudentID   sql.NullInt32
}

type Student struct {
	ID        int32
	LastName  string
	FirstName string
}

type StudentCourse struct {
	StudentID int32
	CourseID  int32
}

type StudentCourseAverage struct {
	ID          int32
	CourseName  string
	StudentName string
	Average     int32
}

type Unite struct {
	ID        int32
	UniteName string
}
